BASE: ['2UBFC-rPPG_RHYTHMMAMBA_ROISGP_V110.yaml']
TRAIN:
  MODEL_FILE_NAME: UBFC_UBFC_UBFC_RhythmMamba_ROISGPM_Full_v110
  LOSS:
    TIME_WEIGHT: 0.5
    FREQ_CE_WEIGHT: 1.0
    FREQ_KL_WEIGHT: 0.0
    FREQ_STD: 3.0
    ROI_PHASE_WEIGHT: 0.03
    HARMONIC_WEIGHT: 0.02
    AUX_HR_WEIGHT: 0.05
    AUX_HR_STD: 3.0
