BASE: ['2UBFC-rPPG_RHYTHMMAMBA_ROISGPM_FULL_V110.yaml']
TRAIN:
  EPOCHS: 8
  MODEL_FILE_NAME: UBFC_UBFC_UBFC_RhythmMamba_ROISGPM_Warm_v110
  LOSS:
    TIME_WEIGHT: 0.5
    FREQ_CE_WEIGHT: 1.0
    FREQ_KL_WEIGHT: 0.0
    FREQ_STD: 3.0
    ROI_PHASE_WEIGHT: 0.01
    HARMONIC_WEIGHT: 0.005
    AUX_HR_WEIGHT: 0.01
    AUX_HR_STD: 3.0
MODEL:
  RESUME: "/experiment0/user/PreTrainedModels/UBFC-rPPG_SizeW128_SizeH128_ClipLength160_DataTypeStandardized_DataAugNone_LabelTypeStandardized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse/UBFC_UBFC_UBFC_RhythmMamba_LossOpt_v105_Time05Full_Epoch21.pth"
  RHYTHMMAMBA:
    ROI_RESIDUAL_SCALE: 0.15
    LOAD_STRICT: False
