BASE: ['2UBFC-rPPG_RHYTHMMAMBA_LOSSOPT_V105_TIME05_FULL.yaml']
TRAIN:
  EPOCHS: 22
  MODEL_FILE_NAME: UBFC_UBFC_UBFC_RhythmMamba_ROI_v110
MODEL:
  RHYTHMMAMBA:
    USE_ROI_STEM: True
    ROI_COUNT: 5
    ROI_RESIDUAL_SCALE: 0.15
    RETURN_AUX: True
