BASE: ['2UBFC-rPPG_RHYTHMMAMBA_ROISGPM_WARM_LR1E6_V110.yaml']
TOOLBOX_MODE: only_test
TEST:
  USE_LAST_EPOCH: False
INFERENCE:
  MODEL_PATH: /experiment0/user/PreTrainedModels/UBFC-rPPG_SizeW128_SizeH128_ClipLength160_DataTypeStandardized_DataAugNone_LabelTypeStandardized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse/UBFC_UBFC_UBFC_RhythmMamba_ROISGPM_WarmLR1e6_v110_Epoch2.pth
