BASE: ['2UBFC-rPPG_RHYTHMMAMBA_AUGFIX_V102.yaml']
TRAIN:
  MODEL_FILE_NAME: UBFC_UBFC_UBFC_RhythmMamba_MambaOpt_v103_State32DP015
TEST:
  USE_LAST_EPOCH: True
MODEL:
  RHYTHMMAMBA:
    DEPTH: 24
    EMBED_DIM: 96
    MLP_RATIO: 2
    DROP_PATH_RATE: 0.15
    MAMBA_D_STATE: 32
    MAMBA_D_CONV: 4
    MAMBA_EXPAND: 2
    MULTI_TEMPORAL_PATHS: 3
