BASE: ['2UBFC-rPPG_RHYTHMMAMBA_AUGFIX_V102.yaml']
TRAIN:
  MODEL_FILE_NAME: UBFC_UBFC_UBFC_RhythmMamba_LossOpt_v104_ValKL005STD3
  LOSS:
    TIME_WEIGHT: 0.2
    FREQ_CE_WEIGHT: 1.0
    FREQ_KL_WEIGHT: 0.05
    FREQ_STD: 3.0
  DATA:
    BEGIN: 0.0
    END: 0.60
VALID:
  DATA:
    BEGIN: 0.60
    END: 0.72
TEST:
  USE_LAST_EPOCH: False
  DATA:
    BEGIN: 0.60
    END: 0.72
